<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VideojuegoSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('videojuegos')->insert([
            [
                'titulo' => 'Cyberpunk 2077',
                'descripcion' => 'Un RPG de aventura y acción de mundo abierto ambientado en Night City.',
                'genero' => 'RPG / FPS',
                'plataforma' => 'PC / PS5 / Xbox',
                'precio' => 59.99,
                'stock' => 20,
                'fecha_lanzamiento' => '2020-12-10',
                'imagen' => 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/header.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Elden Ring',
                'descripcion' => 'Álzate, Sinluz, y conviértete en el señor del Círculo en las Tierras Intermedias.',
                'genero' => 'RPG / Acción',
                'plataforma' => 'PC / PS5 / Xbox',
                'precio' => 49.99,
                'stock' => 10,
                'fecha_lanzamiento' => '2022-02-25',
                'imagen' => 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/header.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'God of War Ragnarök',
                'descripcion' => 'Kratos y Atreus deben viajar a cada uno de los Nueve Reinos.',
                'genero' => 'Acción / Aventura',
                'plataforma' => 'PS5 / PC',
                'precio' => 69.99,
                'stock' => 8,
                'fecha_lanzamiento' => '2022-11-09',
                'imagen' => 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1593500/header.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Grand Theft Auto V',
                'descripcion' => 'Tres criminales arriesgan todo en una serie de atracos en Los Santos.',
                'genero' => 'Acción / Mundo Abierto',
                'plataforma' => 'PC / PS5 / Xbox',
                'precio' => 29.99,
                'stock' => 40,
                'fecha_lanzamiento' => '2013-09-17',
                'imagen' => 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/271590/header.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Spider-Man Remastered',
                'descripcion' => 'Peter Parker lucha contra el crimen organizado y villanos icónicos en Nueva York.',
                'genero' => 'Acción / Aventura',
                'plataforma' => 'PC / PS5',
                'precio' => 59.99,
                'stock' => 15,
                'fecha_lanzamiento' => '2022-08-12',
                'imagen' => 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1817070/header.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Red Dead Redemption 2',
                'descripcion' => 'La vida épica de Arthur Morgan al final de la era de los forajidos.',
                'genero' => 'Aventura / Western',
                'plataforma' => 'PC / PS4 / Xbox',
                'precio' => 59.99,
                'stock' => 25,
                'fecha_lanzamiento' => '2018-10-26',
                'imagen' => 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1174180/header.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'The Witcher 3: Wild Hunt',
                'descripcion' => 'Conviértete en Geralt de Rivia, un cazador de monstruos profesional.',
                'genero' => 'RPG / Fantasía',
                'plataforma' => 'Multiplataforma',
                'precio' => 39.99,
                'stock' => 100,
                'fecha_lanzamiento' => '2015-05-19',
                'imagen' => 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/292030/header.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Resident Evil 4',
                'descripcion' => 'Leon S. Kennedy debe rescatar a la hija del presidente en un pueblo europeo.',
                'genero' => 'Terror / Acción',
                'plataforma' => 'PC / PS5 / Xbox',
                'precio' => 59.99,
                'stock' => 35,
                'fecha_lanzamiento' => '2023-03-24',
                'imagen' => 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2050650/header.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Forza Horizon 5',
                'descripcion' => 'Tu aventura Horizon definitiva en los paisajes de México.',
                'genero' => 'Carreras',
                'plataforma' => 'PC / Xbox',
                'precio' => 59.99,
                'stock' => 20,
                'fecha_lanzamiento' => '2021-11-09',
                'imagen' => 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1551360/header.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'PUBG: BATTLEGROUNDS',
                'descripcion' => 'Salta, saquea y sobrevive en el Battle Royale original.',
                'genero' => 'Shooter / Battle Royale',
                'plataforma' => 'PC / Consolas',
                'precio' => 0.00,
                'stock' => 999,
                'fecha_lanzamiento' => '2017-12-20',
                'imagen' => 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/578080/header.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
